# -*- coding: utf-8 -*-
"""contagemRegressiva

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D19dp_4t46tRvMrnvIolIgkg7xk7jkFn
"""

from time import sleep 

for i in range (10, 0, -1):
    print(i)
    sleep(0.5)
print('Decolar...')